Anoosha
FoodOntology/foodon pull request #177
Opened 2021-12-22 22:29 UTC by Anoosha-Sehar

Genome Tracker terms

2021-12-22 22:37 UTC, Anoosha-Sehar reviewed
**green powder supplement:** Added parent term '`multi-vitamin and multi-mineral supplemen`t' instead of '`botanical supplement with multi-vitamin/mineral`'. As definition of 'green powder supplement' says that it is also made from seaweed, not exactly sure if seaweed comes under the category of plants? It's a green algae, which makes it plant like protist. But I think it's not a true plant.

2021-12-22 23:19 UTC, ddooley requested changes
Hi Anoosha!  Sorry I didn't catch this earlier, but we should add all additives to the FoodOn Robot Tables Dietary Additives tab instead of directly into the foodon-edit.owl file.  I can then rerun the robot command and have those additives appear via import. Ok?

2021-12-22 23:19 UTC, ddooley commented on src/ontology/foodon-edit.owl
> +AnnotationAssertion(obo:IAO_0000115 obo:FOODON_00004147 "A dietary supplement to receive the full nutritional benefits from eating whole fish while eliminating the cooking, tasting and chewing."@en)
I think this could be simplified to "A dietary supplement made from protein derived from marine animals".

2021-12-22 23:54 UTC, Anoosha-Sehar commented
> Hi Anoosha! Sorry I didn't catch this earlier, but we should add all additives to the FoodOn Robot Tables Dietary Additives tab instead of directly into the foodon-edit.owl file. I can then rerun the robot command and have those additives appear via import. Ok?

Sure, no worries! I will add them in Robot file. Then maybe I should revert these commits.

2021-12-23 00:27 UTC, Anoosha-Sehar commented
I've added the terms in FoodOn Robot Tables/Dietary Supplement gsheet. Reverting all the commits except one 'new mexico Chile powder'.

2021-12-23 01:34 UTC, ddooley commented
Ok, indeed commits would need reverting, or just (oy!) drop pull request branch and just do the chili powder one.

2021-12-23 02:14 UTC, merged